DEF_HELPER_N -> DEF_HELPER_FLAGS_N
PPC64/qemu pull request #87
Opened 2022-05-11 11:27 UTC by mferst

In our "PowerISA Vector/VSX instruction batch" patch series, rth noted[1] that helpers that only access vector registers should be declared with `DEF_HELPER_FLAGS_N` and `TCG_CALL_NO_RWG`. We fixed helpers in that series, but there are older helpers that could use the same optimization.

Guided by the presence of `env` as the first argument, in patches 1~4 we change helpers that do not have access to the `cpu_env` pointer to modify any globals. Then, we change other helpers that receive `cpu_env` but do not use it and apply the same fix, taking the opportunity to move them to decodetree.

[1] https://lists.gnu.org/archive/html/qemu-ppc/2022-02/msg00568.html

2022-05-11 13:24 UTC, vcoracolombo requested changes
Looks really good, nice job. Just one nitpick:  target/ppc: Use TCG_CALL_NO_RWG_SE in fsel helper  commit message doesn't say anything about moving to decodetree. I think we could add this :)

Otherwise, just fix the macro call order

2022-05-13 14:29 UTC, luporl commented on target/ppc/fpu_helper.c
> +uint64_t helper_FSEL(uint64_t arg1, uint64_t arg2, uint64_t arg3)
Why it's necessary to change part of the helpers' name to uppercase?

2022-05-13 14:43 UTC, luporl approved these changes
I haven't checked all the details, but the changes look good to me.

2022-05-13 14:49 UTC, luporl commented on target/ppc/fpu_helper.c
> +uint64_t helper_FSEL(uint64_t arg1, uint64_t arg2, uint64_t arg3)
Ok, thanks for the clarification.

2022-05-16 19:40 UTC, alqotel approved these changes
LGTM!

2022-05-25 15:56 UTC, mferst commented
Merged: https://lists.gnu.org/archive/html/qemu-ppc/2022-05/msg00453.html

2022-05-25 15:56 UTC, closed without merging